.TH BKHIVE 1 "November 2007" "Version 1.1.1"

.SH NAME
.B bkhive
dumps the syskey bootkey from a Windows NT/2K/XP/Vista system hive.
.SH SYNOPSIS
bkhive <system hive> <key file>
.SH EXAMPLE
bkhive /mnt/ntfs/WINDOWS/system32/config/system out
.SH AUTHOR
This manual page was written by Adam Cecile <gandalf@le-vert.net> for the Debian system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
.SH SEE ALSO
.br
.B samdump2(1)
.br
.B ophcrack(1)
