// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ch2_vulnerable_json_endpoint {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtAge;
		
		protected System.Web.UI.WebControls.TextBox txtLine1;
		
		protected System.Web.UI.WebControls.TextBox txtLine2;
		
		protected System.Web.UI.WebControls.TextBox txtCity;
		
		protected System.Web.UI.WebControls.TextBox txtState;
		
		protected System.Web.UI.WebControls.TextBox txtZIP;
		
		protected System.Web.UI.WebControls.TextBox txtFirst;
		
		protected System.Web.UI.WebControls.TextBox txtMiddleName;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.Button btnSubmitNewUser;
		
		protected System.Web.UI.WebControls.TextBox txtUserList;
		
		protected System.Web.UI.WebControls.Button btnListUsers;
	}
}
